#url=https://ntdcbdev.nabard.in:36000//fininfra/ui/SSOLogin.jsp
#url=https://bbssl19.bbssl.com:33333/fininfra/ui/SSOLogin.jsp
#userid=BBSSL1
#password=bbssl@123
#userid2=BBSSL8
#password2=bbssl@1234
#url=https://cbsuat.batccb.in:10027/fininfra/ui/SSOLogin.jsp
#userid=BHU07
#password=bbssl@123
#userid1=BHU02
#password1=bbssl@123
#userid2=BBSSL54
#password2=bbssl@123



#trainee
url=https://bbssl19.bbssl.com:33333/fininfra/ui/SSOLogin.jsp
userid=CHRISTINA1
password=christy@1234
userid1=CHRISTINA1
password1=christy@1234
userid2=CHRISTINA
password2=christy@1234


