#trainee
url=https://bbssl19.bbssl.com:33333/fininfra/ui/SSOLogin.jsp
userid=CHRISTINA
password=christy@1234
userid1=CHRISTINA1
password1=christy@1234
userid2=BBSSL85
password2=bbssl@123
userid3=PRIYA
password3=pri@1234

